/** Dev seed viral pattern rows — mirrors migration 0062 inserts. */
export const SEED_VIRAL_PATTERNS = [
  {
    platform: 'tiktok',
    topic: 'morning routine productivity',
    framework: 'routine-rewrite',
    hook_type: 'contrarian',
    emotion: 'inspiration',
    curiosity_trigger: 'What if your morning routine is sabotaging your focus?',
    retention_strategy: 'pattern interrupt at 0:08 + open loop payoff',
    shareability_score: 82,
    saveability_score: 74,
    virality_score: 88,
    story_quality_score: 79,
    framework_confidence: 91,
    raw_analysis: { trend: 'working_now', niche: 'productivity' },
  },
  {
    platform: 'tiktok',
    topic: 'psychology myths debunked',
    framework: 'belief-shift',
    hook_type: 'curiosity',
    emotion: 'surprise',
    curiosity_trigger: 'Everyone believes this — neuroscience says otherwise',
    retention_strategy: 'stack 3 proofs then belief flip at 0:22',
    shareability_score: 79,
    saveability_score: 68,
    virality_score: 85,
    story_quality_score: 81,
    framework_confidence: 89,
    raw_analysis: { trend: 'working_now', niche: 'psychology' },
  },
  {
    platform: 'instagram',
    topic: 'fitness transformation',
    framework: 'transformation-story',
    hook_type: 'story',
    emotion: 'inspiration',
    curiosity_trigger: 'I was stuck for 2 years until I changed one habit',
    retention_strategy: 'before/after contrast + mid-video struggle beat',
    shareability_score: 76,
    saveability_score: 71,
    virality_score: 83,
    story_quality_score: 77,
    framework_confidence: 86,
    raw_analysis: { trend: 'working_now', niche: 'fitness' },
  },
  {
    platform: 'youtube-shorts',
    topic: 'failed startup lessons',
    framework: 'failure-to-wisdom',
    hook_type: 'warning',
    emotion: 'empathy',
    curiosity_trigger: 'I lost $40k — here is the lesson nobody tells founders',
    retention_strategy: 'confession hook + cost escalation + wisdom drop',
    shareability_score: 81,
    saveability_score: 77,
    virality_score: 84,
    story_quality_score: 82,
    framework_confidence: 88,
    raw_analysis: { trend: 'working_now', niche: 'business' },
  },
  {
    platform: 'youtube-shorts',
    topic: '30-day experiment results',
    framework: 'experiment-story',
    hook_type: 'number',
    emotion: 'curiosity',
    curiosity_trigger: 'I tried X for 30 days — the data surprised me',
    retention_strategy: 'daily counter + results reveal at 0:35',
    shareability_score: 78,
    saveability_score: 72,
    virality_score: 86,
    story_quality_score: 80,
    framework_confidence: 87,
    raw_analysis: { trend: 'emerging', niche: 'self-improvement' },
  },
  {
    platform: 'tiktok',
    topic: 'unpopular finance opinion',
    framework: 'contrarian-reveal',
    hook_type: 'contrarian',
    emotion: 'surprise',
    curiosity_trigger: 'Stop doing what every finance guru recommends',
    retention_strategy: 'norm setup → contrarian flip → proof',
    shareability_score: 84,
    saveability_score: 69,
    virality_score: 87,
    story_quality_score: 78,
    framework_confidence: 90,
    raw_analysis: { trend: 'working_now', niche: 'finance' },
  },
  {
    platform: 'instagram',
    topic: 'creator behind the scenes',
    framework: 'creator-spotlight',
    hook_type: 'story',
    emotion: 'curiosity',
    curiosity_trigger: 'How I actually made this viral video (full process)',
    retention_strategy: 'process reveal + tool stack + outcome',
    shareability_score: 73,
    saveability_score: 65,
    virality_score: 79,
    story_quality_score: 76,
    framework_confidence: 84,
    raw_analysis: { trend: 'emerging', niche: 'creator-economy' },
  },
  {
    platform: 'tiktok',
    topic: 'day in my life vlog',
    framework: 'creator-spotlight',
    hook_type: 'story',
    emotion: 'curiosity',
    curiosity_trigger: 'A realistic day building content full-time',
    retention_strategy: 'routine montage + one unexpected conflict',
    shareability_score: 62,
    saveability_score: 55,
    virality_score: 68,
    story_quality_score: 65,
    framework_confidence: 72,
    raw_analysis: { trend: 'oversaturated', niche: 'lifestyle' },
  },
  {
    platform: 'instagram',
    topic: 'generic motivation quotes',
    framework: 'belief-shift',
    hook_type: 'question',
    emotion: 'inspiration',
    curiosity_trigger: 'Are you living your best life?',
    retention_strategy: 'text-on-screen + stock b-roll',
    shareability_score: 45,
    saveability_score: 38,
    virality_score: 52,
    story_quality_score: 48,
    framework_confidence: 55,
    raw_analysis: { trend: 'fading', niche: 'motivation' },
  },
] as const
